num1 = int(input('first number : '))
num2 = int(input('second number : '))
print('thanks!')
print(num1,'+',num2,'=',num1+num2)
print(num1,'-',num2,'=',num1-num2)
print(num1,'/',num2,'=',num1/num2)
print(num1,'*',num2,'=',num1*num2)
input()